#!/bin/sh
# Mock AWS resources and run tests in localstack
#
# Example:
#
#    scripts/cdk/mock -d ./path/to/cdk-directory
#
# Further information:
# See https://localstack.cloud/
#

# Get args
while getopts d: flag
do
    case "${flag}" in
        d) DIRECTORY=${OPTARG};;
    esac
done

# Get variables from root .env
export $(xargs < .env)

if [ -z "$(ls -A $DIRECTORY)" ]; then
    echo "⚠️ CDK source directory is empty"
else
    echo "🚀 Deploying local CDK app"
    cd $DIRECTORY

    # Get variables from cdk .env
    export $(xargs < .env)

    # Set localstack env
    export STAGE=local
    export AWS_REGION=us-east-2

    # Start localstack
    docker-compose -f local/docker-compose.yml up -d

    # Deploy CDK app
    npm install
    npm run build
    npm run cdklocal bootstrap -- --verbose --debug
    npm run cdklocal synth -- --verbose --debug
    npm run cdklocal diff -- --verbose --debug
    npm run cdklocal deploy -- --all --require-approval never --verbose --debug

    # Stop localstack
    # docker-compose -f $DIRECTORY/local/docker-compose.yml down -d
fi